// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOPpKsEM80z1PftuVvWV_uaxiJVeABs8',
    appId: '1:280333007538:web:fc19a32580c2455ceda7ab',
    messagingSenderId: '280333007538',
    projectId: 'todo-a9b0d',
    authDomain: 'todo-a9b0d.firebaseapp.com',
    storageBucket: 'todo-a9b0d.firebasestorage.app',
    measurementId: 'G-14DS2HN3NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAYW2mAosTsuZ4zS_f03Eb9m7JbgrVMW8',
    appId: '1:280333007538:android:36b409916c299a26eda7ab',
    messagingSenderId: '280333007538',
    projectId: 'todo-a9b0d',
    storageBucket: 'todo-a9b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vr71Q-grVqWKjZGg8jbdTvnLljuzlTg',
    appId: '1:280333007538:ios:582c0deb17d7d137eda7ab',
    messagingSenderId: '280333007538',
    projectId: 'todo-a9b0d',
    storageBucket: 'todo-a9b0d.firebasestorage.app',
    iosBundleId: 'com.example.manafea',
  );
}
