# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for android app distribution"
  lane :test do

     sh "flutter clean"
     sh "flutter build apk --release --flavor production -t lib/main_production.dart"
    firebase_app_distribution(
      app: "1:280333007538:android:62015bb72780fdc4eda7ab",


      firebase_cli_token:"1//03zj7mlYQS5hKCgYIARAAGAMSNwF-L9Iry6WBVCa6Gc-zgqjgO1A3x_9SNGCoTwX7bPPpWwnb-wMJLMEC4_5RHAvB8uadVftiRpI",
     testers: "abwalshykhmhmd990@gmail.com,belalscg@gmail.com",
     android_artifact_type:'APK',
     android_artifact_path:  "D:/android_projects/manafea/build/app/outputs/apk/release/app-release.apk",
     release_notes:"last version",
    )

  end
end

